### ISSUE TITLE
[Feature Request]  Billiards Environment

### ISSUE THREAD

**Issue by liamb315** [liamb315/TheConsciousnessPrior#1]
Need to replicate the billiards environment [Sutskever et al. (2009)](https://papers.nips.cc/paper/3567-the-recurrent-temporal-restricted-boltzmann-machine).

**Comment by duguyue100** [comment]
the original environment is very well documented 
here: http://www.cs.utoronto.ca/~ilya/code/2008/RTRBM.tar
I can wrap it in a class, but do we want any additional features?

**Comment by darshanime** [comment]
This was written in Python 2.5 and numpy 1.1. I think we should rewrite this with the latest versions.

**Comment by ischurov** [comment]
@darshanime works under current python 2.7 with minor changes (should replace `scipy.weave` with `weave`).

**Comment by darshanime** [comment]
I'll vote to rewrite it to gain more insight in the code and also use Py3
which is current.

**Comment by duguyue100** [comment]
I've updated a billiards implementation. it's written in python 2, but should be fine with Python 3.
I know this is not a place to fight on python versions. but I suggest people should keep both python 2 and 3 in mind when we are writing the software.

**Comment by liamb315** [comment]
I agree with @duguyue100.

**Comment by liamb315** [comment]
@darshanime I merged this code, but if you send me a PR for Python 3, I'll happily merge that.
