### ISSUE TITLE
Consciousness Attention Mechanism

### ISSUE THREAD

**Issue by liamb315** [liamb315/TheConsciousnessPrior#9]
As written in the proposal and the sketched observational computation graph, the attention mechanisms are discrete selections (hard-attention in the standard nomenclature).  This is not meant to be a definitive constraint; it's an open question how we would like to surface 'unconscious' information to the conscious state.  Further, the simplest iteration of this is attending over elements in a vector, but we may need to be able to generalize to attention over vectors, or more abstractly, the ability to have attention inform the selection of a particular fixed point attractor (as in Hopfield networks).

**Comment by liamb315** [comment]
As a first pass, I am using the selection mechanisms from https://arxiv.org/pdf/1701.06538.pdf.  This has implementation in the tensor2tensor library (https://github.com/tensorflow/tensor2tensor/blob/master/tensor2tensor/utils/expert_utils.py)

**Comment by odellus** [comment]
Hey is there a place you can show me what you're working on? Is it already in the code?
